apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-hzc3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qfkm-tenant/mc-two-scenarios/devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-hzc3@sha256:c95297a734f133ce8cc3e720111b51c6bf521138533a03d72d03902eeb2119fd
        name: my-java-springboot
        resources: {}
status: {}
